title: [Repositório IFCE]
description: [Repositório para os trabalhos desenvolvidos no IFCE.]
url: https://robertolccj.github.io
src: https://github.com/robertolccj/ensino/IFCE

exclude: [LICENSE, README.md, .gitignore]
